### ISSUE TITLE
can't receive skype message using cli 

### ISSUE THREAD

**Issue by cletsimon** [radutopala/skype-bot-php#1]
```
php skype.phar conversation:activity 8:cletsimon test
Conversation: Activity created.
```

```
php skype.phar conversation:activity 8:cletsimon 'test'
Conversation: Activity created.
```

```
php skype.phar conversation:activity '8:cletsimon' 'test'
Conversation: Activity created.
```

Am I missing something?

**Comment by radutopala** [comment]
@cletsimon first thing, have you auth? If yes, then there may be a problem that resides for some time in Skype Bot's endpoints, see https://community.skype.com/t5/Skype-Bot-Developers/gp-p/Bot_devs discussions.

**Comment by cletsimon** [comment]
@radutopala yes, I have auth (client app id and client secret)
and reauth also after this notice `You should re-auth in the following 10 minutes.`

thank you for prompt reply 🙇

**Comment by radutopala** [comment]
@cletsimon pls see my comment https://github.com/radutopala/skype-bot-php/issues/5#issuecomment-233393706
