### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by alexfd** [radutopala/skype-bot-php#12]
Does this work with microsoft live accounts?

I try `php skype.phar auth user@example.com` followed by the password and it fails with:

> PHP Notice:  Undefined index: expires_in in phar:///home/skype/skype.phar/src/Skype/Client.php on line 101
> PHP Stack trace:
> PHP   1. {main}() /home/skype/skype.phar:0
> PHP   2. require() /home/skype/skype.phar:10
> PHP   3. Symfony\Component\Console\Application->run() phar:///home/skype/skype.phar/bin/skype:32
> PHP   4. Symfony\Component\Console\Application->doRun() phar:///home/skype/skype.phar/vendor/symfony/console/Application.php:123
> PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///home/skype/skype.phar/vendor/symfony/console/Application.php:192
> PHP   6. Symfony\Component\Console\Command\Command->run() phar:///home/skype/skype.phar/vendor/symfony/console/Application.php:844
> PHP   7. Skype\Command\AuthCommand->execute() phar:///home/skype/skype.phar/vendor/symfony/console/Command/Command.php:259
> PHP   8. Symfony\Component\Console\Helper\QuestionHelper->ask() phar:///home/skype/skype.phar/src/Skype/Command/AuthCommand.php:47
> PHP   9. Symfony\Component\Console\Helper\QuestionHelper->validateAttempts() phar:///home/skype/skype.phar/vendor/symfony/console/Helper/QuestionHelper.php:65
> PHP  10. call_user_func:{phar:///home/skype/skype.phar/vendor/symfony/console/Helper/QuestionHelper.php:399}() phar:///home/skype/skype.phar/vendor/symfony/console/Helper/QuestionHelper.php:399
> PHP  11. Skype\Command\AuthCommand->Skype\Command\{closure}() phar:///home/skype/skype.phar/vendor/symfony/console/Helper/QuestionHelper.php:399
> PHP  12. Skype\Client->auth() phar:///home/skype/skype.phar/src/Skype/Command/AuthCommand.php:43

.skype says the following:
> error: unauthorized_client
> error_description: "AADSTS70001: Application with identifier 'user' was not found in the directory microsoft.com\r\nTrace ID: 7134af5e-bfa8-4ade-994f-f0bd96472b00\r\nCorrelation ID: c31d5930-dc73-4483-bc1b-2af169ac7bbe\r\nTimestamp: 2017-07-24 18:02:53Z"
> error_codes:
>     - 70001
> timestamp: '2017-07-24 18:02:53Z'
> trace_id: 7134af5e-bfa8-4ade-994f-f0bd96472b00
> correlation_id: c31d5930-dc73-4483-bc1b-2af169ac7bbe
> expires_in: 1500919373

I assume it's not getting the full "user@example.com"? I tried escaping the "@" but no luck.

**Comment by radutopala** [comment]
@alexfd you should use your real username instead of `user@example.com`. Closing..

**Comment by alexfd** [comment]
@radutopala thanks for answering, I think you refer to using the classic way, where you could have some_user_123 and a password and you would log in with that, however now you cannot register using this anymore.  See https://superuser.com/a/980908.

You can only register with your email OR a phone number. When registering with an email the username is displayed in the form of "live:myname" which is extracted from the email address, hinting that it's connected to microsoft live service. Trying to log in with that bit will not work.

**Comment by radutopala** [comment]
@alexfd as it says here: https://github.com/radutopala/skype-bot-php#cli .. you need to enter a `Client Id` and a `Client Secret` .. fetch those from https://dev.botframework.com
