### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by idealley** [radutopala/skype-bot-php#2]
Can you update the dependencies of the lib? 

Installing I have the following error:

```
    - Conclusion: remove symfony/console v3.0.8
    - Conclusion: don't install symfony/console v3.0.8
    - radutopala/skype-bot-php 1.0.0 requires symfony/console ^2.8 -> satisfiable by symfony/console[v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8].
    ...
    - Installation request for symfony/console (locked at v3.0.8) -> satisfiable by symfony/console[v3.0.8]
```

**Comment by radutopala** [comment]
@idealley I need to update `phpdocumentor/reflection-docblock` to a newer version as well, for this to work. Will try to allocate some time soon to do this.

**Comment by radutopala** [comment]
@idealley got some time now, updates done, check `dev-master` or `1.1.0`, should now be working with both Symfony ^2.8 and ^3.

**Comment by idealley** [comment]
Thank you it worked perfectly with the flag `--prefer-source dev-master`
