### ISSUE TITLE
Webhook url for Skype Bot Framework V3

### ISSUE THREAD

**Issue by ralphjay24** [radutopala/skype-bot-php#4]
is your repo has a function on getting the message and the one who send(skype user detail) from a skype bot?

I want to make a webhook site using your library. 

Thank you in advance

BR

**Comment by radutopala** [comment]
@ralphjay24 this library is not intended for working with the Skype webhooks, for now. Therefore it cannot receive messages from Skype.

My suggestion is for you to create a server application with a public url and add this url to the Bot setup.

**Comment by ralphjay24** [comment]
ah Thank you @radutopala 
sorry for misleading here :bow:
