### ISSUE TITLE
Skype Bot php on php < 5.6

### ISSUE THREAD

**Issue by ralphjay24** [radutopala/skype-bot-php#7]
We have a production server running in php 5.4 and we need to implement skype bot php in that version for compatibility.

When I test it, only guzzle library has a php version issues. See screenshots.

Is it possible that skype-bot-php can run on lower version of guzzle (< 6.0) or php(< 5.6) rather?

_Only this 3 errors has been occured._
![selection_104](https://cloud.githubusercontent.com/assets/10727982/17010825/1e24c52c-4f3a-11e6-82a9-db9e43676ff7.png)

For testing, this is my php version

```
php -v
PHP 5.4.42 (cli) (built: Jul 20 2016 19:14:58) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by radutopala** [comment]
@ralphjay24 PHP versions before 5.6 are not maintained anymore, http://php.net/supported-versions.php. You should upgrade. All libraries will or should be moved to PHP>=5.6.

**Comment by ralphjay24** [comment]
@radutopala I see. thanks I think we need it to upgrade.
