### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by hillelcoren** [radutopala/skype-bot-php#8]
I've checked the code, it looks like it currently supports messages. Will attachments also be supported?

I've tried getting it to work by manually crafting the JSON response but haven't been successful. 

Thanks for the great library!

**Comment by radutopala** [comment]
@hillelcoren I'll look into adding more of the Skype endpoints once I'll get back from vacation 😄  .. somewhere around mid-end of August.

**Comment by hillelcoren** [comment]
Awesome, enjoy your vacation! 

I managed to get it working, I was using the v2 endpoint and needed to change to v3.

**Comment by radutopala** [comment]
@hillelcoren feel free to create a PR with this improvement. Tx

**Comment by hillelcoren** [comment]
I haven't been using your library, if you're interested you can see my (in progress) code here:

https://github.com/invoiceninja/invoiceninja/blob/develop/app/Http/Controllers/BotController.php
